include: package:lint/analysis_options.yaml


analyzer:
  strong-mode:
     implicit-casts: true
#     implicit-dynamic: false


linter:
  rules:
        constant_identifier_names: false
        implicit-cast: true
        implicit-dynamic: true
        sort_pub_dependencies: false
        avoid_function_literals_in_foreach_calls-dynamic: false
        avoid_init_to_null: false


